# Generated by Django 4.2 on 2024-01-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_initial'),
    ]

    operations = [
    ]
