# Generated by Django 5.0 on 2024-01-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_post_tags_alter_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='App.tag'),
        ),
    ]
